// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lytjrwhmeujzxhmcgghg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5dGpyd2htZXVqenhobWNnZ2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzA0MDYsImV4cCI6MjA4ODU0NjQwNn0.Bkx1c_HerOlWyLGihSS5DdWyR0izNg1fEsEOsV84_Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});